# Generated by Django 4.1 on 2023-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("plataforma", models.CharField(max_length=30)),
                ("desarrolladora", models.CharField(max_length=40)),
                ("año", models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("fecha", models.IntegerField()),
                ("genero", models.CharField(max_length=30)),
            ],
        ),
    ]
