# Generated by Django 4.1.5 on 2023-02-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_contacto1_inicio1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto1',
            old_name='email',
            new_name='camada',
        ),
        migrations.RenameField(
            model_name='contacto1',
            old_name='nombre',
            new_name='curso',
        ),
    ]
